// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace KOIFARMSHOP.Data.Models;

public partial class AnimalImage
{
    public int AimageId { get; set; }

    public int? AnimalId { get; set; }

    public string ImageUrl { get; set; }

    public virtual Animal Animal { get; set; }
}