// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace KOIFARMSHOP.Data.Models;

public partial class ProductImage
{
    public int PimageId { get; set; }

    public int? ProductId { get; set; }

    public string ImageUrl { get; set; }

    public virtual Product Product { get; set; }
}