// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace KOIFARMSHOP.Data.Models;

public partial class Promotion
{
    public int PromotionId { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public DateOnly? StartDate { get; set; }

    public DateOnly? EndDate { get; set; }

    public decimal? DiscountPercent { get; set; }

    public string Status { get; set; }

    public virtual ICollection<OrderPromotion> OrderPromotions { get; set; } = new List<OrderPromotion>();

    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();
}